apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: raid6
  namespace: openshift-storage
spec:
  deviceClass: raid6
  erasureCoded:
    codingChunks: 0
    dataChunks: 0
  failureDomain: host
  mirroring: {}
  replicated:
    replicasPerFailureDomain: 1
    size: 3
  statusCheck:
    mirror: {}
