apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: odf-private
  namespace: openshift-storage
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "enp27s0f0.2049",
    "mode": "bridge",
    "ipam": {
      "type": "whereabouts",
      "range": "192.168.0.0/24"
    }
  }'
